// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Vxg6ttLxpQgSALDqMAWBGhLSDzlFEhU',
    appId: '1:508824904584:web:33a8e7302ffa802eca103d',
    messagingSenderId: '508824904584',
    projectId: 'chorebuddies-6a970',
    authDomain: 'chorebuddies-6a970.firebaseapp.com',
    storageBucket: 'chorebuddies-6a970.firebasestorage.app',
    measurementId: 'G-5S4FQBCYWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqxAGN2QKc5Xu-2SSUN6JVjozi1qQ8fpw',
    appId: '1:508824904584:android:041db8028ea970b0ca103d',
    messagingSenderId: '508824904584',
    projectId: 'chorebuddies-6a970',
    storageBucket: 'chorebuddies-6a970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDzdMkLboTWV2D-pp1djJW2VbMRvDGQY',
    appId: '1:508824904584:ios:4edf86408d1adae2ca103d',
    messagingSenderId: '508824904584',
    projectId: 'chorebuddies-6a970',
    storageBucket: 'chorebuddies-6a970.firebasestorage.app',
    iosBundleId: 'com.example.chorebuddiesFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdDzdMkLboTWV2D-pp1djJW2VbMRvDGQY',
    appId: '1:508824904584:ios:4edf86408d1adae2ca103d',
    messagingSenderId: '508824904584',
    projectId: 'chorebuddies-6a970',
    storageBucket: 'chorebuddies-6a970.firebasestorage.app',
    iosBundleId: 'com.example.chorebuddiesFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Vxg6ttLxpQgSALDqMAWBGhLSDzlFEhU',
    appId: '1:508824904584:web:373178a39492712bca103d',
    messagingSenderId: '508824904584',
    projectId: 'chorebuddies-6a970',
    authDomain: 'chorebuddies-6a970.firebaseapp.com',
    storageBucket: 'chorebuddies-6a970.firebasestorage.app',
    measurementId: 'G-6TEW0JQ3TW',
  );
}
